### ISSUE TITLE
TG SIGNALS

### ISSUE THREAD

**Issue by MrAbdelaziz** [burnb/signaller#1]
Hello,

thank you for your efforts in developing this project. I have successfully implemented GRPC /Docker in my system, and it's been a valuable addition. However, I've noticed that the project currently lacks a feature that would greatly enhance its functionality: the ability to send signals to Telegram when a position is created, updated, or closed.

Thank you for your attention to this matter, and I look forward to seeing how this project continues to evolve.

Best regards,

**Comment by burnb** [comment]
Hello @MrAbdelaziz ! 
This project was made with an idea of single responsibility of the service, so it's just generate signals and all the logic like strategy, trading operations or alerts notifications should be in the separate service application which would be connected to the Signaller by GRPC.

**Comment by MrAbdelaziz** [comment]
I truly appreciate your quick response and for clarifying the project's design.

In light of your explanation, I'm curious to know if you've already implemented a separate service for trading operations or alerts, or if you could provide some guidance and recommendations on how to do so effectively. Any insights or best practices you can share in this regard would be immensely valuable.

Once again, thank you for your attention and for the invaluable work you've invested in this project.

**Comment by MrAbdelaziz** [comment]
`
package main
import (
	"context"
	"fmt"
	"github.com/burnb/signaller/pkg/grpc/api"
	"go.uber.org/zap"
	"log"
)

func main() {
	logger, _ := zap.NewProduction()
	defer logger.Sync()

	logger.Info("Start")

	address := "localhost:8080"
	publishers := []string{"03E3F39C5C1802D69D58044F1E4F44C6", "2622535B7F0F517A69074A404BB76605"}

	client := api.NewClient(address, publishers, logger)

	err := client.Init(context.Background())
	if err != nil {
		logger.Error("Client initialization error", zap.Error(err))
	}

	positionEventChan, err := client.Subscribe(context.Background())
	if err != nil {
		log.Fatalf("Subscription error: %v", err)
	}

	for event := range positionEventChan {
		fmt.Printf("Received Position Event: ID=%d, Symbol=%s, TraderUID=%s\n", event.PositionId, event.Symbol, event.TraderUid)
	} } `
i found that there is an API in the services so i implement it like that, if i want to listen to all publishers existing in the DB/SERVER like only to subscribe and stream without Pubs ? how can implement that

**Comment by MrAbdelaziz** [comment]
everything is clear now after understanding the structure & code , thank you again @burnb  for this art !
